<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BrewHub - Login</title>
    <link rel="stylesheet" href="../css/style_login.css" />
    <link rel="icon" type="image/png" href="../assets/icons/favicon.ico" />
  </head>
  <body>
    <div class="container">
      <!-- Lado esquerdo: logo -->
      <div class="left-side">
        <img src="../assets/image/logo.png" alt="BrewHub Logo" />
      </div>
      <!-- Lado direito: formulário -->
      <div class="right-side">
        <h2>Login</h2>
        <form action="<? route('users.authenticate') ?>" method="POST">
          <label for="email">E-mail</label>
          <input id="email" type="email" name="user[email]" required>

          <label for="password">Senha</label>
          <input id="password" type="password" name="user[password]" required />
          <button type="submit">Entrar</button>
        </form>
      </div>
    </div>
  </body>
</html>
