<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BrewHub - Cadastro de Usuário</title>
    <link rel="icon" type="image/png" href="../assets/icons/favicon.ico" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />

    <!-- Estilo Customizado -->
    <link rel="stylesheet" href="../aplications/css/style.css" />
  </head>
  <body>
    <!-- Navbar -->
    <header>
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">BrewHub</a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#"
                  >Cadastrar Receitas</a
                >
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Cadastrar Materiais</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Relatorios</a>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Usuários</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <!-- Formulário -->
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6 bg-light shadow rounded-4 p-4">
          <h2 class="text-center text-brown mb-4">Cadastro de Usuário</h2>
          <form class="row g-3">
            <div class="col-md-6">
              <label for="userName" class="form-label">Nome de Usuários</label>
              <input type="userName" class="form-control" id="usarName" />
            </div>
            <div class="col-md-6">
              <label for="inputEmail4" class="form-label">Email</label>
              <input type="email" class="form-control" id="inputEmail4" />
            </div>
            <div class="col-md-6">
              <label for="inputPassword4" class="form-label">Password</label>
              <input type="password" class="form-control" id="inputPassword4" />
            </div>
            <div class="col-md-6">
              <label for="inputPasswordConfirmation" class="form-label"
                >Password Confirmations</label
              >
              <input
                type="password"
                class="form-control"
                id="inputPassword4Confirmation"
              />
            </div>
            <div class="col-12">
              <label for="inputAddress" class="form-label">Address</label>
              <input
                type="text"
                class="form-control"
                id="inputAddress"
                placeholder="1234 Main St"
              />
            </div>
            <div class="col-12">
              <label for="inputAddress2" class="form-label">Address 2</label>
              <input
                type="text"
                class="form-control"
                id="inputAddress2"
                placeholder="Apartment, studio, or floor"
              />
            </div>
            <div class="col-md-6">
              <label for="inputCity" class="form-label">City</label>
              <input type="text" class="form-control" id="inputCity" />
            </div>
            <div class="col-md-4">
              <label for="inputState" class="form-label">State</label>
              <select id="inputState" class="form-select">
                <option selected>Choose...</option>
                <option>...</option>
              </select>
            </div>
            <div class="col-md-2">
              <label for="inputZip" class="form-label">Zip</label>
              <input type="text" class="form-control" id="inputZip" />
            </div>
            <div class="col-12">
              <div class="form-check">
                <input
                  class="form-check-input"
                  type="checkbox"
                  id="gridCheck"
                />
                <label class="form-check-label" for="gridCheck">
                  Check me out
                </label>
              </div>
            </div>
            <div class="col-12">
              <button type="submit" class="btn btn-primary">Sign in</button>
            </div>
          </form>
        </div>
      </div>
    </div>

    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6 bg-light shadow rounded-4 p-4">
          <h2 class="text-center text-brown mb-4">Cadastro de Usuário</h2>
          <form>
            <div class="mb-3">
              <label class="form-label text-brown">Nome de Usuário</label>
              <input type="text" class="form-control" required />
            </div>
            <div class="mb-3">
              <label class="form-label text-brown">E-mail</label>
              <input type="email" class="form-control" required />
            </div>
            <div class="mb-3">
              <label class="form-label text-brown">Senha</label>
              <input type="password" class="form-control" required />
            </div>
            <div class="mb-3">
              <label class="form-label text-brown">Confirmação de Senha</label>
              <input type="password" class="form-control" required />
            </div>
            <div class="mb-3">
              <label class="form-label text-brown">Tipo de Usuário</label>
              <select class="form-select">
                <option>Auxiliar Cervejeiro</option>
                <option>Mestre Cervejeiro</option>
                <option>Super Admin</option>
              </select>
            </div>
            <div class="mb-3">
              <label class="form-label text-brown">Permissões</label>
              <div class="form-check">
                <input class="form-check-input" type="checkbox" id="receita" />
                <label class="form-check-label" for="receita"
                  >Tela de Criação de Receita</label
                >
              </div>
              <div class="form-check">
                <input class="form-check-input" type="checkbox" id="insumos" />
                <label class="form-check-label" for="insumos"
                  >Cadastro de Insumos</label
                >
              </div>
              <div class="form-check">
                <input class="form-check-input" type="checkbox" id="usuarios" />
                <label class="form-check-label" for="usuarios"
                  >Cadastro de Usuários</label
                >
              </div>
              <div class="form-check">
                <input
                  class="form-check-input"
                  type="checkbox"
                  id="relatorio"
                />
                <label class="form-check-label" for="relatorio"
                  >Extração de Relatório</label
                >
              </div>
              <div class="form-check">
                <input class="form-check-input" type="checkbox" id="versao" />
                <label class="form-check-label" for="versao"
                  >Testes de Versão</label
                >
              </div>
            </div>
            <button type="submit" class="btn btn-brown w-100">Cadastrar</button>
          </form>
        </div>
      </div>
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>
